server:
  port: 7070

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Account Service (Context-path: /account)
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/api/v1/account/**
              filters:
                - StripPrefix=2

