server:
  port: 9030
  servlet:
    context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-intelligence-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: qwen/qwen3-next-80b-a3b-instruct:free
          temperature: 0.0
      embedding:
        options:
          model: qwen/qwen3-embedding-8b

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret-key: erdtfg5434567y8uijbvfgyhjbfde4567ujnbc342g54g3v2ccexqwd
